---
apiVersion: v1
kind: ConfigMap
metadata:
  name: predictions-live
  namespace: rwml
data:
  # Quote them!!! - by Marius
  # https://12factor.net/config
  PREDICTIONS_MLFLOW_TRACKING_URI: "http://mlflow-tracking.mlflow.svc.cluster.local:80"
  PREDICTIONS_MLFLOW_TRACKING_USERNAME: "user"
  PREDICTIONS_MLFLOW_TRACKING_PASSWORD: "6440921D-2493-42AA-BE40-428CD753D81D"
  PREDICTIONS_RISINGWAVE_HOST: "risingwave.risingwave.svc.cluster.local"
  PREDICTIONS_RISINGWAVE_PORT: "4567"
  PREDICTIONS_RISINGWAVE_USER: "root"
  PREDICTIONS_RISINGWAVE_PASSWORD: ""
  PREDICTIONS_RISINGWAVE_DATABASE: "dev"
  PREDICTIONS_RISINGWAVE_SCHEMA: "public"
  PREDICTIONS_RISINGWAVE_INPUT_TABLE: "technical_indicators"
  PREDICTIONS_RISINGWAVE_OUTPUT_TABLE: "predictions"
  PREDICTIONS_PAIR: "BTC/USD"
  PREDICTIONS_PREDICTION_HORIZON_SECONDS: "300"
  PREDICTIONS_CANDLE_SECONDS: "60"
  PREDICTIONS_MODEL_VERSION: "latest"