---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-indicators
  namespace: rwml
  labels:
    app: technical-indicators
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technical-indicators
  template:
    metadata:
      labels:
        app: technical-indicators
    spec:
      containers:
      - name: technical-indicators
        image: ghcr.io/williamjudge94/technical_indicators:latest
        imagePullPolicy: Always
        env:
        - name: TECHNICAL_INDICATORS_APP_NAME
          value: "technical_indicators-prod"
        - name: TECHNICAL_INDICATORS_DEBUG
          value: "false"
        - name: TECHNICAL_INDICATORS_LOG_LEVEL
          value: "WARNING"
        - name: TECHNICAL_INDICATORS_LOG_FORMAT
          value: "json"
        - name: TECHNICAL_INDICATORS_KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: TECHNICAL_INDICATORS_KAFKA_INPUT_TOPIC
          value: "candles-prod"
        - name: TECHNICAL_INDICATORS_KAFKA_OUTPUT_TOPIC
          value: "technical_indicators-prod"
        - name: TECHNICAL_INDICATORS_KAFKA_CONSUMER_GROUP
          value: "technical_indicators_prod_group"
        - name: TECHNICAL_INDICATORS_CANDLE_SECONDS
          value: "60"
        - name: TECHNICAL_INDICATORS_MAX_CANDLES_IN_STATE
          value: "70"
        - name: TECHNICAL_INDICATORS_TABLE_NAME_IN_RISINGWAVE
          value: "technical_indicators"
        - name: TECHNICAL_INDICATORS_RISINGWAVE_HOST
          value: "risingwave.risingwave.svc.cluster.local"
        - name: TECHNICAL_INDICATORS_RISINGWAVE_PORT
          value: "4567"
        - name: TECHNICAL_INDICATORS_RISINGWAVE_USER
          value: "root"
        - name: TECHNICAL_INDICATORS_RISINGWAVE_PASSWORD
          value: ""
        - name: TECHNICAL_INDICATORS_RISINGWAVE_DATABASE
          value: "dev"
        - name: TECHNICAL_INDICATORS_SMA_PERIODS
          value: "7,14,21,60"
        - name: TECHNICAL_INDICATORS_EMA_PERIODS
          value: "7,14,21,60"
        - name: TECHNICAL_INDICATORS_RSI_PERIODS
          value: "7,14,21,60"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi