---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades
  labels:
    app: trades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades
  template:
    metadata:
      labels:
        app: trades
    spec:
      containers:
      - name: trades
        image: trades:dev
        imagePullPolicy: Never # Use the local image
        env:
        - name: TRADES_APP_NAME
          value: trades-dev
        - name: TRADES_KAFKA_TOPIC_NAME
          value: trades-dev
        - name: TRADES_KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: TRADES_KAFKA_TOPIC
          value: "trades"
        - name: TRADES_KAFKA_TOPIC_PARTITIONS
          value: "2"
        - name: TRADES_PRODUCT_IDS
          value: '["BTC/USD", "ETH/USD", "SOL/USD", "XRP/USD"]'
        - name: TRADES_LIVE_OR_HISTORICAL
          value: "live"