---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles-live
  labels:
    app: candles-live
spec:
  replicas: 2
  selector:
    matchLabels:
      app: candles-live
  template:
    metadata:
      labels:
        app: candles-live
    spec:
      containers:
      - name: candles
        image: candles:dev
        imagePullPolicy: Never # Use the local image
        env:
        - name: CANDLES_APP_NAME
          value: "candles-dev"
        - name: CANDLES_KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: CANDLES_KAFKA_INPUT_TOPIC
          value: "trades-dev"
        - name: CANDLES_KAFKA_OUTPUT_TOPIC
          value: "candles-dev"
        - name: CANDLES_KAFKA_CONSUMER_GROUP
          value: "candles_dev_live_group"
        - name: CANDLES_PROCESSING_MODE
          value: "live"
        - name: CANDLES_CANDLE_SECONDS
          value: "60"